INSERT INTO users (username, email, user_password) VALUES ('user_1', 'user1@example.com', 'password_1');
INSERT INTO users (username, email, user_password) VALUES ('user_2', 'user2@example.com', 'password_2');
INSERT INTO users (username, email, user_password) VALUES ('user_3', 'user3@example.com', 'password_3');
INSERT INTO users (username, email, user_password) VALUES ('user_4', 'user4@example.com', 'password_4');
INSERT INTO users (username, email, user_password) VALUES ('user_5', 'user5@example.com', 'password_5');
INSERT INTO users (username, email, user_password) VALUES ('user_6', 'user6@example.com', 'password_6');
INSERT INTO users (username, email, user_password) VALUES ('user_7', 'user7@example.com', 'password_7');
INSERT INTO users (username, email, user_password) VALUES ('user_8', 'user8@example.com', 'password_8');
INSERT INTO users (username, email, user_password) VALUES ('user_9', 'user9@example.com', 'password_9');
INSERT INTO users (username, email, user_password) VALUES ('user_10', 'user10@example.com', 'password_10');
INSERT INTO users (username, email, user_password) VALUES ('user_11', 'user11@example.com', 'password_11');
INSERT INTO users (username, email, user_password) VALUES ('user_12', 'user12@example.com', 'password_12');
INSERT INTO users (username, email, user_password) VALUES ('user_13', 'user13@example.com', 'password_13');
INSERT INTO users (username, email, user_password) VALUES ('user_14', 'user14@example.com', 'password_14');
INSERT INTO users (username, email, user_password) VALUES ('user_15', 'user15@example.com', 'password_15');
INSERT INTO users (username, email, user_password) VALUES ('user_16', 'user16@example.com', 'password_16');
INSERT INTO users (username, email, user_password) VALUES ('user_17', 'user17@example.com', 'password_17');
INSERT INTO users (username, email, user_password) VALUES ('user_18', 'user18@example.com', 'password_18');
INSERT INTO users (username, email, user_password) VALUES ('user_19', 'user19@example.com', 'password_19');
INSERT INTO users (username, email, user_password) VALUES ('user_20', 'user20@example.com', 'password_20');

INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (1, '910 Random St', 'City_13', 'State_37', '662526');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (1, '788 Random St', 'City_33', 'State_36', '529579');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (1, '422 Random St', 'City_86', 'State_43', '764792');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (1, '811 Random St', 'City_92', 'State_3', '854654');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (1, '393 Random St', 'City_50', 'State_31', '488401');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (1, '871 Random St', 'City_5', 'State_31', '770347');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (2, '507 Random St', 'City_59', 'State_10', '710216');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (2, '170 Random St', 'City_69', 'State_33', '216799');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (2, '430 Random St', 'City_92', 'State_37', '453839');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (3, '561 Random St', 'City_93', 'State_27', '880801');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (3, '299 Random St', 'City_51', 'State_46', '473705');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (3, '733 Random St', 'City_51', 'State_14', '231816');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (3, '272 Random St', 'City_58', 'State_23', '878278');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (3, '291 Random St', 'City_27', 'State_1', '575562');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (4, '171 Random St', 'City_12', 'State_28', '518796');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (4, '693 Random St', 'City_88', 'State_13', '748610');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (4, '881 Random St', 'City_82', 'State_4', '781704');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (5, '147 Random St', 'City_57', 'State_4', '229192');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (5, '298 Random St', 'City_10', 'State_19', '784836');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (5, '403 Random St', 'City_76', 'State_39', '334812');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (5, '690 Random St', 'City_68', 'State_43', '237681');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (6, '501 Random St', 'City_53', 'State_10', '205178');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (6, '540 Random St', 'City_31', 'State_39', '509609');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (6, '831 Random St', 'City_2', 'State_48', '547461');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (7, '819 Random St', 'City_41', 'State_38', '422718');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (7, '163 Random St', 'City_30', 'State_30', '438795');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (7, '248 Random St', 'City_19', 'State_10', '127648');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (8, '883 Random St', 'City_99', 'State_32', '308419');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (9, '978 Random St', 'City_78', 'State_20', '704576');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (10, '309 Random St', 'City_20', 'State_4', '529048');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (11, '199 Random St', 'City_6', 'State_23', '381039');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (11, '403 Random St', 'City_85', 'State_30', '317260');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (12, '677 Random St', 'City_53', 'State_38', '241436');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (13, '554 Random St', 'City_19', 'State_12', '736296');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (13, '202 Random St', 'City_41', 'State_33', '238155');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (13, '766 Random St', 'City_74', 'State_20', '591101');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (13, '422 Random St', 'City_89', 'State_50', '346325');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (13, '395 Random St', 'City_73', 'State_44', '544862');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (14, '269 Random St', 'City_52', 'State_1', '458292');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (14, '689 Random St', 'City_25', 'State_47', '724179');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (14, '343 Random St', 'City_50', 'State_41', '605138');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (14, '571 Random St', 'City_95', 'State_20', '722757');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (15, '518 Random St', 'City_3', 'State_19', '477208');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (15, '674 Random St', 'City_44', 'State_6', '442151');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (15, '324 Random St', 'City_29', 'State_30', '535593');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (16, '611 Random St', 'City_5', 'State_27', '267591');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (17, '370 Random St', 'City_52', 'State_45', '932989');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (17, '580 Random St', 'City_65', 'State_2', '410911');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (17, '988 Random St', 'City_21', 'State_18', '134115');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (17, '406 Random St', 'City_66', 'State_25', '702039');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (17, '779 Random St', 'City_79', 'State_11', '102520');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (18, '824 Random St', 'City_31', 'State_43', '895259');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (18, '672 Random St', 'City_94', 'State_27', '990536');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (18, '723 Random St', 'City_19', 'State_14', '393843');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (18, '505 Random St', 'City_56', 'State_27', '795689');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (18, '373 Random St', 'City_8', 'State_17', '482395');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (18, '200 Random St', 'City_19', 'State_1', '660039');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (19, '618 Random St', 'City_1', 'State_12', '132514');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (20, '374 Random St', 'City_35', 'State_24', '355034');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (20, '216 Random St', 'City_78', 'State_30', '978531');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (20, '988 Random St', 'City_30', 'State_16', '486725');
INSERT INTO user_address (user_id, street, city, state, pincode) VALUES (20, '796 Random St', 'City_41', 'State_12', '810819');